### ISSUE TITLE
摄像头分辨率无法设置成800X600

### ISSUE THREAD

**Issue by vvhh2002** [espressif/esp-dev-kits#15]
摄像头分辨率无法设置成800X600，jpeg.c 报错。同时，驱动的Buffer似乎也会有问题

**Comment by ChenZhengwei20190741** [comment]
hi, 尝试这种方法：https://github.com/espressif/esp-dev-kits/issues/9

**Comment by vvhh2002** [comment]
谢谢，问题解决 ，什么时候esp32-camera 项目能支持s2就好了
