### ISSUE TITLE
esp32-s2-kaluga-1/README_cn.md has no English translation (AEGHB-177)

### ISSUE THREAD

**Issue by pevsonic** [espressif/esp-dev-kits#2]
Hiya,

Any chance of an English translation of esp32-s2-kaluga-1/README_cn.md? 

I can try and use google translate but was wondering if you have a ready translated version I can use first!

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
