### ISSUE TITLE
请问出厂的时候，搭配的出厂程序源码在哪里？提供的吗？

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/esp-dev-kits#21]
请问出厂的时候，搭配的出厂程序源码在哪里？提供的吗？

**Comment by leeebo** [comment]
Please check here for the factory bin of [esp32-s2-kaluga-1](https://github.com/espressif/esp-dev-kits/tree/master/esp32-s2-kaluga-1/examples/factory)
