### ISSUE TITLE
Ask about the pin usage of SPI TF

### ISSUE THREAD

**Issue by coollofty** [espressif/esp-dev-kits#22]
I use two SPI devices now, one is SPI Master. This is currently working properly. It uses some pins from GPIO9~14. Since a camera is also connected, the camera PCLK uses GPIO33, so I want to is it feasible to connect an SPI TF and the threes works fine together?

**Comment by leeebo** [comment]
@coollofty SPI as a bus can theoretically connect multiple devices with different CS pins, you can try it.
