### ISSUE TITLE
ESP32-S2-HMI-Devkit-1 Battery NOT included

### ISSUE THREAD

**Issue by FBEZ** [espressif/esp-dev-kits#29]
In the ESP32-S2-HMI-Devkit it's mentioned that  the kit is equipped with the 1950mAh battery but it's not
https://github.com/espressif/esp-dev-kits/blame/master/esp32-s2-hmi-devkit-1/README.md#L18

Shouldn't this line be replaced with "The 1950mAh battery is not included"?

**Comment by Real-YuZhe** [comment]
Due to strict regulation on battery export, we are shipping ESP32-S2-HMI-DevKit-1 without battery outside the Chinese mainland. You can buy the Li-ion battery for iphone5, no capacity limitation.

**Comment by pinkeen** [comment]
This is great to know. Just a clarification needed - this is the 5G battery to be exact, right?

**Comment by sukesh-ak** [comment]
What about the battery connector? Any spec?
