### ISSUE TITLE
No SDCard contents available for ESP32-S2-HMI-Devkit-1 Smart Panel Example

### ISSUE THREAD

**Issue by meetroger** [espressif/esp-dev-kits#30]
As it requires img_fetch_list[] to load resources for LVGL. There are many resources missing: /Icon, /Pic, /UI etc.

**Comment by Real-YuZhe** [comment]
Hi, example has been updated and resources are stored in flash now.

**Comment by meetroger** [comment]
Great! it works, thank you!
