### ISSUE TITLE
eclipe放入例程之后缺少头文件

### ISSUE THREAD

**Issue by Sean8869** [espressif/esp-dev-kits#32]
../main/include/qcloud.h:15:10: fatal error: esp_qcloud_iothub.h: No such file or directory
 #include "esp_qcloud_iothub.h"
          ^~~~~~~~~~~~~~~~~~~~~
头文件要怎么和原来的IDF结合，比较正式的操作应该是怎么样的？

**Comment by Real-YuZhe** [comment]
克隆该仓库，更新子模块后，直接在 examples 下的各个例程文件夹内编译工程，不要将文件夹拷贝至其他目录，因为依赖于 components 文件夹下的组件
