### ISSUE TITLE
Hmi-devkit-1  smart-panel   check for image resources??

### ISSUE THREAD

**Issue by tommly119** [espressif/esp-dev-kits#34]
/* Resources loading list */ 
 Missing file  such as  S:/UI/humid.bin...

哪里下载这些文件拷贝进SD卡呢？

**Comment by Real-YuZhe** [comment]
Hi, example has been updated and resources are stored in flash now.

**Comment by dazhen18** [comment]
how to store binary flles(pictures) to flash

**Comment by dazhen18** [comment]
thanks，it’s been solved
