### ISSUE TITLE
ESP32-S2-Kaluga 1 openocd Jtag debugging settings in Vscode using Mac OS

### ISSUE THREAD

**Issue by kalpanavengala** [espressif/esp-dev-kits#35]
Hi,
I have purchased ESP-32-S2-Kaluga-1 board because it is having inbuilt JTAG adapter. I have installed ESP-idf extension via VScode in my mac os. There is no proper manual on how to do the openocd settings for Kaluga -1 board in mac os.

Please provide me proper guidance on how to set the openocd configuration for kaluga -1 board using VScode in mac. last few weeks onwards am troubleshooting but no result. Please help me am not able to do debugging...

**Comment by TDA-2030** [comment]
Chapter [JTAG Debugging](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-guides/jtag-debugging/index.html) of `ESP-IDF Programming Guide` may help you.
