### ISSUE TITLE
LCD datasheet

### ISSUE THREAD

**Issue by dronecz** [espressif/esp-dev-kits#37]
Hi, 

is it posible to share datasheet for 4.3" LCD? 

Thanks for info 😉

**Comment by Real-YuZhe** [comment]
Hi,

Display controller : 
[RM68120.pdf](https://github.com/espressif/esp-dev-kits/files/6920765/RM68120.pdf)

 LCD Panel : 
[TK043F15.PDF](https://github.com/espressif/esp-dev-kits/files/6920762/TK043F15.PDF)

**Comment by dronecz** [comment]
Many thanks 🙂
