### ISSUE TITLE
ILI9341 LCD initialization sequence bug

### ISSUE THREAD

**Issue by zhongluqiang** [espressif/esp-dev-kits#39]
https://github.com/espressif/esp-dev-kits/blob/master/esp32-s2-kaluga-1/components/lcd/lcd.c#L269

bug code:
```c
/* Memory access contorl, MX=MY=0, MV=1, ML=0, BGR=1, MH=0 */
lcd_write_cmd(0x36);
lcd_write_byte(0b11000000);
```

fixed:
```c
/* Memory access contorl, MX=MY=0, MV=1, ML=0, BGR=1, MH=0 */
lcd_write_cmd(0x36);
lcd_write_byte(0x28);
```

The fix is ported from V4.2 and has been tested on a ESP32-S2-Kaluga-1 Kit v1.3 demo board by examples/lcd demo.

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
