### ISSUE TITLE
example camera run with error on ESP32-S2-Kaluga-1 v1.3 idf/release 4.3.1

### ISSUE THREAD

**Issue by RobsXiao** [espressif/esp-dev-kits#44]
i run camera on ESP32-S2-Kaluga-1 v1.3,but get the error:
![image](https://user-images.githubusercontent.com/693129/137264742-092d3675-aba2-4a63-8614-8faddd64c6cd.png)

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
