### ISSUE TITLE
esp32-s2-kaluga-1 编译失败 (AEGHB-180)

### ISSUE THREAD

**Issue by tiger1116** [espressif/esp-dev-kits#48]
../main/esp_camera.h:71:10: fatal error: sensor.h: No such file or directory
 #include "sensor.h"
          ^~~~~~~~~~
利用实例的camera，没有修改，就这样报错了
请问如何解决？谢谢

**Comment by Lzw655** [comment]
很抱歉没有及时回答你的问题！
由于这个问题已经失去时效性了，我将在一周后关闭它。如果你还需要解决这个问题，请留言或新开一个 issue，谢谢！
