### ISSUE TITLE
ESP32 Kaluga example - mono mp3 plays at double speed - esp32-s2-kaluga-1/examples/touch_audio

### ISSUE THREAD

**Issue by georgik** [espressif/esp-dev-kits#49]
How to simulate: replace MP3 in the example with Mono MP3.
Observed behaviour: Playback speed is double.
Expected behaviour: Playback speed of stereo and mono MP3 is the same.

**Comment by ISR-AlanYang** [comment]
Change channel_format to I2S_CHANNEL_FMT_RIGHT_LEFT when playing mono audio files. It works for me. Hope it helps.
i2s_config_t i2s_config = {
        ...
        .channel_format = /*I2S_CHANNEL_FMT_RIGHT_LEFT*/I2S_CHANNEL_FMT_ONLY_RIGHT,                           /* this setting works for mono audio files */
        ...
    };
