### ISSUE TITLE
Kaluga factory image for ST7789 boards missing  (AEGHB-183)

### ISSUE THREAD

**Issue by maartenwrs** [espressif/esp-dev-kits#50]
esp32-s2-kaluga-1/examples/factory has two factory animation binary files intended for the Kaluga-1s that come with TFTs with ILI9341 controllers.  However, there are no  corresponding binary files available for the Kaluga-1s that come with TFTs with ST7789 controllers.  This is problematic for those that wish to restore their Kalugas to factory settings.

A workaround is to extract the factory binary when it is new before overwriting it, such as with:
 esptool.py --chip esp32s2 -p /dev/ttyUSB1 --b 115200 read_flash 0 0x400000 factory.bin
after which it can be restored with:
 esptool.py --chip esp32s2 -p /dev/ttyUSB1 -b 115200 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m --flash_size 4MB 0x0 factory.bin

I am opening this for those that did not consider this before overwriting the flash, including myself.

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
