### ISSUE TITLE
esp-dev-kits/esp32-s2-kaluga-1/examples/lcd 根本点不亮

### ISSUE THREAD

**Issue by flfq** [espressif/esp-dev-kits#52]
是淘宝买的V1.3版本
IC驱动两个版本都试过，屏点不亮

**Comment by TDA-2030** [comment]
这里的驱动看起来和idf格格不入，我觉得你应该试试这个：https://github.com/espressif/esp-idf/tree/master/examples/peripherals/spi_master/lcd
