### ISSUE TITLE
Example IDF version requirement specification

### ISSUE THREAD

**Issue by fishjump** [espressif/esp-dev-kits#53]
Hello there,

I tried to build the camera example of esp32-s2-kaluga-1, and got compile errors with the latest esp-idf (2/25/2022, 6:56:18 AM 8363f88cd5c8bad44c6b2ffda42cd7cc9996e64c).

I tried to checkout to v4.4 and compiled successfully.

My board is kaluga v1.3, and I tried on my m1 MBA and Archlinux PC. I think the latest idf cannot work on other machines too.

Please mention that in the README

BR, Yue

**Comment by TDA-2030** [comment]
You are right, idf v5.0 does not provide good compatibility 😞
