### ISSUE TITLE
Eclipse esp32 Devit Kit s2 kaluga issue 

### ISSUE THREAD

**Issue by Gavo4** [espressif/esp-dev-kits#57]
Hi There,

I am using Eclipse Version: 4.23.0.v20220308-0310 and ESP-IDF v4.4.1-dirty and I can't seem to get the LCD and Camera samples from the Github to work at all!,

I needed to include this line of code below for the Camera Example to compile but is still does not run, I get a fizzy screen

#define esp_camera_init 

the LCD I can't get to work, please see error below

../main/main.c: In function 'esp_photo_display':
../main/main.c:80:19: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
     jpg2rgb565(buf, read_bytes, rgb565, JPG_SCALE_NONE);
                   ^
../main/main.c:80:31: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
     jpg2rgb565(buf, read_bytes, rgb565, JPG_SCALE_NONE);
                               ^
../main/main.c:80:39: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
     jpg2rgb565(buf, read_bytes, rgb565, JPG_SCALE_NONE);
                                       ^
../main/main.c:80:39: error: statement with no effect [-Werror=unused-value]
     jpg2rgb565(buf, read_bytes, rgb565, JPG_SCALE_NONE);
               ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
ninja: build stopped: subcommand failed.
Build complete (4 errors, 0 warnings): C:\Users\gavo\Documents\PlatformIO\esp-dev-kits-master\esp32-s2-kaluga-1\examples\lcd\build
C:\Users\gavo\.espressif\python_env\idf4.4_py3.7_env\Scripts\python.exe C:\Users\gavo\esp-idf-v4.4.1\tools\idf_size.py C:/Users/gavo/Documents/PlatformIO/esp-dev-kits-master/esp32-s2-kaluga-1/examples/lcd/build/esp32-s2-hmi.map
C:\Users\gavo\.espressif\python_env\idf4.4_py3.7_env\Scripts\python.exe C:\Users\gavo\esp-idf-v4.4.1\components\partition_table\gen_esp32part.py C:\Users\gavo\Documents\PlatformIO\esp-dev-kits-master\esp32-s2-kaluga-1\examples\lcd\build\partition_table\partition-table.bin
Total time taken to build the project: 39 887 ms

I cleaned all the builds and still can't get it work, please advise as I would like to test the unit

Version is V1.3

Regards,

Gavin

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
