### ISSUE TITLE
ESP32-S2-HMI-DevKit-1 with LVGL version 8.x => Not working (IDF-Version 4.3) (IDFGH-8413)

### ISSUE THREAD

**Issue by VigneshAkshaya** [espressif/esp-dev-kits#58]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have tried HMI development on ESP32-S2-HMI-DevKit-1 with LVGL version 7.11, working successfully.
![with LVGL 7 11](https://user-images.githubusercontent.com/87164915/192970624-c4ac3945-2530-4fb8-af04-44263e8941d1.png)

But it is not working with the same code porting to LVGL version to 8.x
![with LVGL 8 x](https://user-images.githubusercontent.com/87164915/192970477-f97a6379-481c-4b9b-a287-2cc48ad498c3.png)

please find attachment for reference,

Any Support ?????

**Comment by Lzw655** [comment]
@VigneshAkshaya Please attach your new code which porting to v8.x.

**Comment by VigneshAkshaya** [comment]
Please find the attachment
[SampleProgramLVGL8.2.zip](https://github.com/espressif/esp-dev-kits/files/9674426/SampleProgramLVGL8.2.zip)

**Comment by Lzw655** [comment]
@VigneshAkshaya I have reviewed your project, and I found there're some uncorrect configurations. You can modify them as follow:
* SampleProgramLVGL8.2/components/lvgl/lv_conf.h:
  * Set `LV_MEM_CUSTOM` to 1
  * Set `LV_MEMCPY_MEMSET_STD` to 1
![Screenshot from 2022-10-08 15-39-42](https://user-images.githubusercontent.com/109257001/194696931-ae6d5541-d00b-441d-bed5-03aad7bba3e3.png)
* SampleProgramLVGL8.2/components/lvgl/lv_port/lvgl_port.c:
  * Modify `disp_drv.hor_res` and `disp_drv.hor_res`
![Screenshot from 2022-10-08 15-40-08](https://user-images.githubusercontent.com/109257001/194697055-d3c3116f-7343-48fd-86e6-347e080fd4fa.png)
  * Modify parameters of `bsp_lcd_flush`
![Screenshot from 2022-10-08 15-40-22](https://user-images.githubusercontent.com/109257001/194697088-f2c2c38f-9c7d-489b-a5a3-e3b14314318a.png)

**Comment by VigneshAkshaya** [comment]
@Lzw655 
I have tried with the above configurations and it is working fine for labels, but I dont know why it is not working for other widgets.

•	Button was created and added to the existing “Hello World “ text – Only “Button” text label is getting displayed.
•	Event was assigned to the button to follow up the button event – It’s not clickable and given event also hasn’t happened.
•	And , widgets such as bar , slider , switch were also tested and only text is getting displayed for all .

Changes I have made,
	main\hello_world_main.c -> btn1 is created and its corresponding event handler .
![image](https://user-images.githubusercontent.com/87164915/195639389-5e307566-95c7-4e88-9e18-a05dc70cde51.png)

Hardware Observation as below

![123](https://user-images.githubusercontent.com/87164915/195639983-cdaab5a5-dcb0-470e-8faf-2106c971901e.png)

**Comment by Lzw655** [comment]
@VigneshAkshaya I checked the file "components\lvgl\lv_conf.h" in your project again, and I found the configuration "LV_USE_THEME_DEFAULT" is set to 0 which should be 1. This caused LVGL's widgets to have no default appearance.

**Comment by Lzw655** [comment]
@VigneshAkshaya Is your problem solved? If so, please close this issue.

**Comment by VigneshAkshaya** [comment]
Hey @Lzw655 , sorry for the delay, I was unavailable for whole past 2 weeks.

•	“LV_USE_THEME_DEFAULT”  was set it to 1.Dsiplay is changed and there was no response on clicking the button
•	I2C Bus and LCD Touch Init are also happening properly . Verified through ESP ERROR CHECK and print statements for all the init functions.
•	LV_EVENT_CLICKED given to the event handler is not working whereas other default events are happening – verified by printing event codes.

![image](https://user-images.githubusercontent.com/87164915/198508048-bf390d11-361d-4889-82f6-49a3482c2ff9.png)

**Comment by Lzw655** [comment]
Sorry for not responding to your question in a timely manner!
Since this problem has lost its time, I will close it after a week. If you still need to solve this problem, please leave a comment or open a new issue, thank you!
