### ISSUE TITLE
esp32-s2-kaluga-1/examples/lcd/main/main.c Title might be mistake

### ISSUE THREAD

**Issue by nemon-** [espressif/esp-dev-kits#59]
esp-dev-kits/blob/master/esp32-s2-kaluga-1/examples/lcd/main/main.c
第一行“/* Camera Example”应该是“/* LCD Example”吧？

**Comment by Lzw655** [comment]
是的，谢谢反馈

**Comment by Lzw655** [comment]
> esp-dev-kits/blob/master/esp32-s2-kaluga-1/examples/lcd/main/main.c 第一行“/* Camera Example”应该是“/* LCD Example”吧？

是的，谢谢反馈
