### ISSUE TITLE
Trouble installing USB Driver for esp32-s2-hmi-devkit-1

### ISSUE THREAD

**Issue by formus14** [espressif/esp-dev-kits#61]
Hello,

Im getting started with the esp32-s2-hmi-devkit-1, but unfortuntally the driver is neither installed by default neither accepting ftdi installation for it.

- I want to ask what dirver shall i installer in order to flash the dev kit

![image](https://user-images.githubusercontent.com/9719340/203564367-00a06661-48e0-4742-be35-b784d386d33a.png)

Thanks in advance

**Comment by Lzw655** [comment]
Hi, you can check [this guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/get-started/establish-serial-connection.html#connect-esp32-s2-to-pc) to install the driver.

**Comment by formus14** [comment]
Thanks @Lzw655 , CP210x: [CP210x USB to UART Bridge VCP Drivers](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers) driver was what i missed.
Works fine now!
