### ISSUE TITLE
如何开启 idf-v5.0  Configuration of PSRAM	Octal, 120M ? (AEGHB-20)

### ISSUE THREAD

**Issue by Easix** [espressif/esp-dev-kits#63]
我在使用 esp-idf v5.0   lcd_rgb面板
  如何开启 PSRAM Octal, 120M ? ，我该怎么做？

**Comment by Lzw655** [comment]
@Easix 请先下载本仓库，然后使用目录下 esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch 文件给 ESP-IDF 打上补丁，具体步骤见[文档](https://github.com/espressif/esp-dev-kits/blob/master/esp32-s3-lcd-ev-board/factory/README.md#idf-patch)

**Comment by Lzw655** [comment]
@Easix 请问你的问题是否已解决，如果解决的话请关闭此 issue，谢谢！
