### ISSUE TITLE
LCD  AVOID TEAR  WHEN SCREEN ROTATION 180 (AEGHB-49)

### ISSUE THREAD

**Issue by Wvirgil123** [espressif/esp-dev-kits#64]
问题: 当删除 ' depends on LCD_EVB_SCREEN_ROTATION_0 '  依赖项时( https://github.com/espressif/esp-dev-kits/blob/71aad98bd60cd5028c070bf299bff102edad58a7/esp32-s3-lcd-ev-board/examples/smart-panel/components/bsp/Kconfig.projbuild#L80),  然后开启avoid tear 功能， 并旋转180°。 但实际效果是无法旋转180°。请问一下是否可以既旋转180°， 又能开启 avoid tear 功能呢？

环境： esp32s3 + RGB565 (480*480)

**Comment by Lzw655** [comment]
@Wvirgil123 因为防撕裂方案是基于 LVGL 的 direct-mode/full-refresh 种模式实现的，LVGL 暂不支持 direct-mode/full-refresh + 软件旋转，见 [issue](https://github.com/lvgl/lvgl/issues/3829)，而且 RGB LCD 屏幕一般也不能设置硬件旋转，所以这个需求暂时无法实现。

**Comment by Lzw655** [comment]
防撕裂方案已进行更新，请参考 [bsp](https://github.com/espressif/esp-bsp/tree/master/esp32_s3_lcd_ev_board)，相关配置项为：BSP_LCD_RGB_DOUBLE_BUFFER、BSP_LCD_RGB_REFRESH_TASK_ENABLE 、BSP_DISPLAY_LVGL_AVOID_TEAR

**Comment by Wvirgil123** [comment]
> 

感谢， 加上这个可以实现x 轴镜像
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/25890961/215320566-b34fe28e-6f2b-4278-a7d0-f42aeceb742c.png">

**Comment by Lzw655** [comment]
不客气，那请关闭此 issue
