### ISSUE TITLE
esp32-s3-lcd-ev-board下的86box_demo无法使用。 (AEGHB-78)

### ISSUE THREAD

**Issue by taxue-alfred** [espressif/esp-dev-kits#66]
esp32-s3-lcd-ev-board下的86box_demo下的CMakeLists.txt写了一行
`set(EXTRA_COMPONENT_DIRS  ../../components)`
但是此目录并没有components文件夹。造成了编译错误，并且menuconfig也无法打开。
在main中看到引入了`esp_board.h`等相关头文件，但是我并没有在当前实例中发现这几个文件。
请问`../../components`中的文件应该如何获取？

**Comment by Lzw655** [comment]
@taxue-alfred 实在抱歉，这个是因为 esp32-s3-lcd-ev-board 最新的 BSP 移到了 [esp-bsp](https://github.com/espressif/esp-bsp/tree/master/esp32_s3_lcd_ev_board) 中，但是 86box_demo 还没有进行更新导致编译错误，我会马上修复好。

（近期 BSP 会有更新优化，Demo 效果也会有提升）

**Comment by taxue-alfred** [comment]
> @taxue-alfred 实在抱歉，这个是因为 esp32-s3-lcd-ev-board 最新的 BSP 移到了 [esp-bsp](https://github.com/espressif/esp-bsp/tree/master/esp32_s3_lcd_ev_board) 中，但是 86box_demo 还没有进行更新导致编译错误，我会马上修复好。
> 
> （近期 BSP 会有更新优化，Demo 效果也会有提升）

好的辛苦你了，我最近刚好也在做示例的调试，没想到碰上了哈哈

**Comment by Lzw655** [comment]
@taxue-alfred Demo 已修复，请拉取试一下，如果没有问题，麻烦关闭此 issue，谢谢

**Comment by taxue-alfred** [comment]
> @taxue-alfred Demo 已修复，请拉取试一下，如果没有问题，麻烦关闭此 issue，谢谢

非常感谢你的修复
由于我看到`sdkconfig.defaults`中打开了PSRAM 120Mhz的补丁，所以我首先尝试了打补丁的操作。但是在IDF根目录执行之后却报了这样的警告
```shell
PS D:\ESP-IDF\IDF_5> git apply D:\Projects\OpenSources\esp-dev-kits\esp32-s3-lcd-ev-board\factory\release5.0_psram_octal_120m.patch
D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:461: trailing whitespace.
# Legacy, F8R8, Flash 120M DDR, PSRAM disable
D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:462: trailing whitespace.

D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:463: trailing whitespace.
CONFIG_SPI_FLASH_USE_LEGACY_IMPL=y
D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:464: trailing whitespace.
CONFIG_ESPTOOLPY_OCT_FLASH=y
D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:465: trailing whitespace.
CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_DTR=y
warning: squelched 13 whitespace errors
warning: 18 lines add whitespace errors.
```
但是操作文档中正常打开应当不弹出提示，请问这样如何解决呢？

**Comment by Lzw655** [comment]
> > @taxue-alfred Demo 已修复，请拉取试一下，如果没有问题，麻烦关闭此 issue，谢谢
> 
> 非常感谢你的修复 由于我看到`sdkconfig.defaults`中打开了PSRAM 120Mhz的补丁，所以我首先尝试了打补丁的操作。但是在IDF根目录执行之后却报了这样的警告
> 
> ```shell
> PS D:\ESP-IDF\IDF_5> git apply D:\Projects\OpenSources\esp-dev-kits\esp32-s3-lcd-ev-board\factory\release5.0_psram_octal_120m.patch
> D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:461: trailing whitespace.
> # Legacy, F8R8, Flash 120M DDR, PSRAM disable
> D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:462: trailing whitespace.
> 
> D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:463: trailing whitespace.
> CONFIG_SPI_FLASH_USE_LEGACY_IMPL=y
> D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:464: trailing whitespace.
> CONFIG_ESPTOOLPY_OCT_FLASH=y
> D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:465: trailing whitespace.
> CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_DTR=y
> warning: squelched 13 whitespace errors
> warning: 18 lines add whitespace errors.
> ```
> 
> 但是操作文档中正常打开应当不弹出提示，请问这样如何解决呢？

这个是 win10 行尾结束符的问题，有些电脑可能会出现这样的报错，你可以在 vscode 右下角（如图）修改补丁文件 LF 或 CRLF 试一下，如果不行，也可以自己新建 .patch 文件，然后复制源文件内容过去
![image](https://user-images.githubusercontent.com/109257001/220253272-b61429fa-c6a6-4b1e-8144-48c796fd23e4.png)

**Comment by taxue-alfred** [comment]
> > > @taxue-alfred Demo 已修复，请拉取试一下，如果没有问题，麻烦关闭此 issue，谢谢
> > 
> > 
> > 非常感谢你的修复 由于我看到`sdkconfig.defaults`中打开了PSRAM 120Mhz的补丁，所以我首先尝试了打补丁的操作。但是在IDF根目录执行之后却报了这样的警告
> > ```shell
> > PS D:\ESP-IDF\IDF_5> git apply D:\Projects\OpenSources\esp-dev-kits\esp32-s3-lcd-ev-board\factory\release5.0_psram_octal_120m.patch
> > D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:461: trailing whitespace.
> > # Legacy, F8R8, Flash 120M DDR, PSRAM disable
> > D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:462: trailing whitespace.
> > 
> > D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:463: trailing whitespace.
> > CONFIG_SPI_FLASH_USE_LEGACY_IMPL=y
> > D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:464: trailing whitespace.
> > CONFIG_ESPTOOLPY_OCT_FLASH=y
> > D:/Projects/OpenSources/esp-dev-kits/esp32-s3-lcd-ev-board/factory/release5.0_psram_octal_120m.patch:465: trailing whitespace.
> > CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_DTR=y
> > warning: squelched 13 whitespace errors
> > warning: 18 lines add whitespace errors.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是操作文档中正常打开应当不弹出提示，请问这样如何解决呢？
> 
> 这个是 win10 行尾结束符的问题，有些电脑可能会出现这样的报错，你可以在 vscode 右下角（如图）修改补丁文件 LF 或 CRLF 试一下，如果不行，也可以自己新建 .patch 文件，然后复制源文件内容过去 ![image](https://user-images.githubusercontent.com/109257001/220253272-b61429fa-c6a6-4b1e-8144-48c796fd23e4.png)

感谢感谢，已经解决，克隆下来默认是`CRLF`，修改为`LF`即可解决。经过测试，即使报warning也可以正常使用。
