### ISSUE TITLE
Typo in documentations for USB Host power options? (AEGHB-133)

### ISSUE THREAD

**Issue by shreeve** [espressif/esp-dev-kits#68]
The documentation at:

     https://espressif-docs.readthedocs-hosted.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-usb-otg/user_guide.html

has the following:

<img width="738" alt="Monosnap ESP32-S3-USB-OTG — esp-dev-kits documentation 2023-04-06 17-07-11" src="https://user-images.githubusercontent.com/142875/230509635-1aefb2a9-1e22-441c-b538-04ec75b20c3d.png">

Isn't this incorrect?

In order for me to use the `USB Host` (USB-A female port), I need to set:

<img width="733" alt="Monosnap Signal 2023-04-06 17-08-15" src="https://user-images.githubusercontent.com/142875/230509721-8bfba051-b31f-44fb-9080-73898219a467.png">

Which is the opposite of what the documentation states.

Am I missing something here?

**Comment by shreeve** [comment]
At a minimum, it seems like the text should be clearer.

**Comment by leeebo** [comment]
Hi @shreeve, the description of the document is correct, although it is a little convoluted.

The symbols in schematic `USB_DEV D+ D-` means the Pins will link to an external USB device (but through Type-A female / Host port)

BTW. you can use the already encapsulated API [bsp esp32_s3_usb_otg](https://components.espressif.com/components/espressif/esp32_s3_usb_otg) to switch ports

**Comment by shreeve** [comment]
I never even knew about the BSP mechanism... pretty cool

**Comment by shreeve** [comment]
There is a nice set of API calls in the source code within the BSP code.

But, where do I find the API documentation for this BSP code?

**Comment by Lzw655** [comment]
> 

There is no API documentation for the BSP code now. You can directly find API information from the [header file](https://github.com/espressif/esp-bsp/blob/master/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h).

**Comment by shreeve** [comment]
@Lzw655 - Ah, ok. Thank you!
