### ISSUE TITLE
Unable to get VBUS (+5V) on the ESP USB (USB Host) port on the ESP32-S3 DevKit C v1.0 board (AEGHB-162)

### ISSUE THREAD

**Issue by shreeve** [espressif/esp-dev-kits#71]
On my ESP32-S3-USB-OTG board, I need to set GPIO 12=>1, 13=>0, 17=>1, 18=>1 in order to enable power to the USB Host port. Otherwise, that port will not be able to supply power to the USB Devices that connect to it.

On my ESP32-S3 DevKitC v1.0 board (see diagram below), I don't see anything that would imply that I have to set those or any other pins. In fact, it looks like both micro USB ports are connected to +5V and GND and that they both have their own D+ and D- pins, which is all that I need.

Unfortunately, I can't see the +5V on the ESP USB port. Instead, I have to get share +5V and GND pins from an external USB A port.

Is there a way for the board to supply the needed +5V (I assume the GND is already working)?

<img width="1080" alt="Monosnap Monosnap 2023-04-26 19-36-06" src="https://user-images.githubusercontent.com/142875/234737843-700907a9-7d2d-44d7-98b2-298b872a887e.png">

**Comment by leeebo** [comment]
Hi @shreeve, For the `esp32-s3-devkitc` board the micro USB port can only act as 5V input, and can not as 5V output. Because there's a diode between the 5V and the VBUS (You can short the diode to get 5V output, but please note the power risks)

**Comment by shreeve** [comment]
@leeebo - Thank you for the information!!!
