### ISSUE TITLE
Link from Espressif site to C3 LCD kit is 404 (AEGHB-247)

### ISSUE THREAD

**Issue by a2800276** [espressif/esp-dev-kits#76]
Just a heads-up. The Espressif site incorrectly links to the C3 LCD Devkit.

URL on Espressif site: https://www.espressif.com/en/solutions/hmi/smart-displays
Existing (incorrect-404) link: https://github.com/espressif/esp-dev-kits/tree/master/esp32-c3-lcd-ev-board
Correct (I assume :) : https://github.com/espressif/esp-dev-kits/tree/master/esp32-c3-lcdkit

**Comment by Lzw655** [comment]
Thank you for reporting this broken link! We will fix it as soon as possible.

**Comment by Lzw655** [comment]
@a2800276 Already Fixed. Thanks for your contributions.
