### ISSUE TITLE
ESP32-S3-USB-OTG factory source code (AEGHB-311)

### ISSUE THREAD

**Issue by TechRelief** [espressif/esp-dev-kits#77]
I see a bin file in the esp-dev-kits repo for the ESP32-S3-USB-OTG board, which presumably is a compiled image.  Where can I find the actual source code for this.
I am new to this board and it would be helpful to look at the code as a starting point on how to program this board.

**Comment by Lzw655** [comment]
@TechRelief Hi, you can find the source code in folder *esp32-s3-usb-otg/examples/factory*.

**Comment by Lzw655** [comment]
@TechRelief If your problem has been resolved, please close this issue. Thank you!

**Comment by TechRelief** [comment]
Did you mean: https://github.com/espressif/esp-dev-kits/blob/master/esp32-s3-usb-otg/examples/factory/main/app_main.c
If so you can close the issue.  Sorry about the dalay got Covid-19 again and am now recovered.

**Comment by Lzw655** [comment]
@TechRelief Yeah. No worries. You can open a new issue if you have any other problems.
