### ISSUE TITLE
请问如何录音？

### ISSUE THREAD

**Issue by coollofty** [espressif/esp-dev-kits#8]
现在的examples里有touch_audio，但是没有实现record。请问如何从I2S读取Microphone的数据？我按照I2S的接口实现了read，但是读出来的都是0

**Comment by ChenZhengwei20190741** [comment]
adf有录音功能,也适配了kaluga1.2, 如果你是1.3,请自行更改管脚.https://github.com/espressif/esp-adf/tree/master/examples/audio_processing/pipeline_passthru
