### ISSUE TITLE
esp32c3 stuck in jtag mode (AEGHB-355)

### ISSUE THREAD

**Issue by LucaCraft89** [espressif/esp-dev-kits#81]
i havbe an esp32 c3 i bought and after flashing a sketch to it and resetting afterwards it is only detected as usb jtag and not a serial (COM) device i tried holding boot while plugging in but no luck

**Comment by Lzw655** [comment]
Hi @LucaCraft89, are you using the ESP32-C3-LCDkit board? If so, it is indeed only detected as a USB JTAG. Because the USB port is directly connected to the chip as below.

![image](https://github.com/espressif/esp-dev-kits/assets/109257001/bed6f404-5d5c-4256-89cc-330cc59f5537)
![image](https://github.com/espressif/esp-dev-kits/assets/109257001/093c1462-45ca-46ec-b06b-f0cd0dd22be1)

**Comment by LucaCraft89** [comment]
Hi @Lzw655 i'm not and before i got the jtag behavior i was able to get the serial port

**Comment by Lzw655** [comment]
Please provide the detailed development board model and version you are currently using.

**Comment by LucaCraft89** [comment]
I got it on AliExpress ![Screenshot_2023-08-28-07-50-30-952_com.alibaba.aliexpresshd.jpg](https://github.com/espressif/esp-dev-kits/assets/85185929/c4e5d97e-dd16-4267-8deb-c1271075e654)

**Comment by Lzw655** [comment]
Well, it's not an official ESP board. Looks like this board directly connects the USB port with the ESP chip as same as the picture I showed before. If so, it should not be detected as a serial (COM) device anyhow.

Please check its scheme or provide it here and I'll check it.

**Comment by LucaCraft89** [comment]
![-1088405692-1489030928.jpg](https://github.com/espressif/esp-dev-kits/assets/85185929/2452a5c1-9dea-4593-8f64-e027c083f60b)

**Comment by Lzw655** [comment]
According to this schematic, the USB port is directly connected to the ESP chip and it should always be detected as a USB JTAG device.

**Comment by leeebo** [comment]
@LucaCraft89 Hi, for the USB-Serial-JTAG controller in ESP32-C3, which has two interfaces, one is a USB serial interface, and the other is a USB JTAG interface. Two new devices should be detected as below:

![image](https://github.com/espressif/esp-dev-kits/assets/16922815/a434fd0e-dabc-43b4-bdba-40f25a486ad6)

If you can not find the serial (COM) device, please re-install the driver using tools like Zadig, choose interface 0, then choose `usbser` or `USB CDC` driver

![image](https://github.com/espressif/esp-dev-kits/assets/16922815/3e19e8b8-e043-4346-82b6-dff178c77e06)

**Comment by LucaCraft89** [comment]
Fact is i don't seee the second one

**Comment by LucaCraft89** [comment]
Ohhh ok i'll try

**Comment by Lzw655** [comment]
Hi @LucaCraft89, if your problem has been resolved, please close this issue. Thank you!

**Comment by LucaCraft89** [comment]
Hi @Lzw655 i have not resolved the issue and still need help with it

**Comment by Lzw655** [comment]
> Hi @Lzw655 i have not resolved the issue and still need help with it

Please describe the detailed issue and @leeebo will help you.
