### ISSUE TITLE
开发板 esp32-s3-lcd-ev-board\examples\86box_smart_panel 中汉字不能显示 (AEGHB-367)

### ISSUE THREAD

**Issue by 13825650991** [espressif/esp-dev-kits#82]
在开发板列程中有些汉字不能显示出来，为什么呢？

![无标题](https://github.com/espressif/esp-dev-kits/assets/80733408/5433ce6c-5569-4e89-b5da-6131164a2980)

**Comment by espressif2022** [comment]
这个字号的码表里面没有对应的字符，需要添加一下
https://lvgl.io/tools/fontconverter

**Comment by 13825650991** [comment]
那如何需要全部简体汉字，如何办？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-dev-kits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-dev-kits] 开发板 esp32-s3-lcd-ev-board\examples\86box_smart_panel 中汉字不能显示 (AEGHB-367) (Issue #82)





 
这个字号的码表里面没有对应的字符，需要添加一下
 https://lvgl.io/tools/fontconverter

**Comment by espressif2022** [comment]
1：要是还是用 map 表的话，就把汉字的范围填进去。

2：可以用这个字库，目前正式 demo github 还没出去，https://components.espressif.com/components/espressif/freetype

**Comment by 13825650991** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-dev-kits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-dev-kits] 开发板 esp32-s3-lcd-ev-board\examples\86box_smart_panel 中汉字不能显示 (AEGHB-367) (Issue #82)





 
1：要是还是用 map 表的话，就把汉字的范围填进去。
 
2：可以用这个字库，目前正式 demo github 还没出去，https://components.espressif.com/components/espressif/freetype

**Comment by Lzw655** [comment]
@13825650991 请问你的问题是否已经解决，如果是的话请关闭此 issue，谢谢!

**Comment by 13825650991** [comment]
通过生成字库文件，并申明，已经可以使用。

**Comment by 13825650991** [comment]
上一个问题已经关闭，现在有一个新的问题，由于github 太难登录，所以只能把问题发在这里了。


title： 在项目中做编码转化的时候，用到c库中的iconv 函数，但是该函数总是返回 -1，errno = 9
代码如下：


int code_convert(char* from_charset,char *to_chartset,char* inbuf,size_t inlen,char *outbuf,size_t outlen)
{
&nbsp; &nbsp; iconv_t cd;
&nbsp; &nbsp; char **pin = &amp;inbuf;
&nbsp; &nbsp; char **pout = &amp;outbuf;
&nbsp; &nbsp; cd = iconv_open(to_chartset,from_charset);
&nbsp; &nbsp; if(cd == 0)
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; ESP_LOGI("ESP_TOOS", "iconv_open =%d\n",cd);
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp; &nbsp; memset(outbuf,0,outlen);
&nbsp; &nbsp; if(iconv(cd,pin,&amp;inlen,pout,&amp;outlen) == -1)
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; switch(errno)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; case EBADF: 		/* Bad file number */
&nbsp; &nbsp; &nbsp; &nbsp; ESP_LOGI("ESP_TOOS", "EBADF\n");
&nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; &nbsp; case E2BIG:
&nbsp; &nbsp; &nbsp; &nbsp; ESP_LOGI("ESP_TOOS", "E2BiG\n");
&nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; &nbsp; case EILSEQ:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ESP_LOGI("ESP_TOOS","EILSEQ\n");
&nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; &nbsp; case EINVAL:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ESP_LOGI("ESP_TOOS","EINVAL\n");
&nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; ESP_LOGI("ESP_TOOS", "errno:%d,iconv =-1\n",errno);
&nbsp; &nbsp; &nbsp; &nbsp; iconv_close(cd);
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp; &nbsp; iconv_close(cd);
&nbsp; &nbsp; *pout ='\0';
&nbsp; &nbsp; return 0;
}


int g2u(char* inbuf,size_t inlen,char* outbuf,size_t outlen)
{
&nbsp; &nbsp; return code_convert("GBK","UTF-8",inbuf, inlen,outbuf,outlen);
}



网上有反映是C库不完整所致，所以请帮忙测试，并生成完整c库，谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-dev-kits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月21日(星期四) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-dev-kits] 开发板 esp32-s3-lcd-ev-board\examples\86box_smart_panel 中汉字不能显示 (AEGHB-367) (Issue #82)





 
@13825650991 请问你的问题是否已经解决，如果是的话请关闭此 issue，谢谢!
