### ISSUE TITLE
ESP-C3-LCDkit 基础入门Demo Flash 输出问题 (IDFGH-11346)

### ISSUE THREAD

**Issue by nixgnauhcuy** [espressif/esp-dev-kits#84]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

我正在学习并使用 `ESP-C3-LCDkit` 开发板，我在使用基础入门工程 `hello_world` 时遇到了问题，内容如下：
![image](https://github.com/espressif/esp-idf/assets/73231354/001ac1e7-94a3-4754-ac64-543db9ae584d)

![image](https://github.com/espressif/esp-idf/assets/73231354/9f863558-cfab-4179-8335-eb220a2fd45e)

开发板只有内部 4Mb flash，但是输出的日志却是拥有外部的 2Mb flash，这是否属于 bug.

**Comment by Lzw655** [comment]
@nixgnauhcuy 你好，这个并不是 bug，开发板内置 flash 是 4M，但是工程的默认配置是将 flash 大小设置为 2M，请通过 `menuconfig` 修改工程的 sdkconfig，具体配置项为：`Serial flasher config` -> `Flash size` -> `4MB`。

**Comment by nixgnauhcuy** [comment]
@Lzw655 感谢你的帮助，我按上述方式尝试后， Flash size 大小正确，但是我还有个疑惑，
![image](https://github.com/espressif/esp-dev-kits/assets/73231354/79d5fdf8-994c-4ce2-86e7-2d3316aebb38)

输出的日志是外部 4m 的 flash，
![image](https://github.com/espressif/esp-dev-kits/assets/73231354/2447f957-eac1-4f8c-a64d-26f4f270e096)

`esp_chip_info` 接口并未设置C3拥有 `features` 为 CHIP_FEATURE_EMB_FLASH，这个工程 config 似乎没有可以修改的地方?

**Comment by Lzw655** [comment]
flash 相对于 ESP 芯片是外置的，而相对于模组（最小系统）是内置的，代码这里是从芯片的角度设置的。

**Comment by nixgnauhcuy** [comment]
好的，我理解了 十分感谢！

**Comment by Lzw655** [comment]
不客气，如果问题已解决的话，请关闭此 issue，谢谢。
