### ISSUE TITLE
esp32-s3-lcd-ev-board  use the same iis pin,  audio playing and recoreding at the same time  ,is it ok ? (AEGHB-442)

### ISSUE THREAD

**Issue by jeq430** [espressif/esp-dev-kits#85]

**Comment by espressif2022** [comment]
Yes, It's ok.
I2S has two channels(BSP_I2S_DOUT and BSP_I2S_DSIN). they can work together.
 You can refer to our demo, when playing music, SR can be worked, too.
https://github.com/espressif/esp-box/tree/master/examples/factory_demo

**Comment by Lzw655** [comment]
Hi @jeq430, do you have any more questions? If not, please close this issue or I'll close it next week.
