### ISSUE TITLE
ESP32-S3-LCD-EV-Board Io for ADC available (AEGHB-612)

### ISSUE THREAD

**Issue by isthaison** [espressif/esp-dev-kits#91]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I want to read analog data from the sensor, what history should I use to ensure that other features work?

**Comment by Lzw655** [comment]
Hi @isthaison, you can use pins as shown below to read analog data. Please check the "NOTE" to know their limitations.
![image](https://github.com/espressif/esp-dev-kits/assets/109257001/e083dfb4-f3b2-4b90-8c33-9c8a5dc3a975)

**Comment by isthaison** [comment]
If so, then in this situation only IO4 pin can be used. no can't use S3's SPI and LED, right?, or is there another way

**Comment by Lzw655** [comment]
Yes.

**Comment by isthaison** [comment]
@Lzw655  
![image](https://github.com/espressif/esp-dev-kits/assets/22739578/bb77bc26-8827-417b-96da-297ca4e502fa) 
Canwe read analog with  Pin?

**Comment by Lzw655** [comment]
Hi @isthaison,

Sorry, the TCA9554 chip can only read digital level 0/1.

**Comment by isthaison** [comment]
If so, then only IO4 and IO19 can be used on this board. but it is used for LED and USB, which is quite inconvenient. If there is an upgrade board, we can always design at least 2 pins for ADC and 2 Digital pins. This will make it easier for developers to develop their own integrations

**Comment by Lzw655** [comment]
You are right. This ESP-S3 development board has a shortage of IO pins due to the integration of RGB screen, audio input, and output functions. The upcoming ESP-P4 development board will provide ample IO pins.

**Comment by isthaison** [comment]
When will the ESP-P4 development board be released? Because I am preparing to deploy the project, in large quantities

**Comment by Lzw655** [comment]
I'm sorry, but there is currently no exact time available.

**Comment by isthaison** [comment]
Somehow, could you sell me one in advance so I can research it first :D

**Comment by Lzw655** [comment]
I'm sorry for not getting back to you sooner. You can contact Espressif's business team to get a sample.

**Comment by isthaison** [comment]
Can I ask for design files (dfx, etc). some format that can be imported into design. instead of the dpf file that the document provides. I am designing an expansion pcb part to connect the expansion pin

**Comment by isthaison** [comment]
![image](https://github.com/espressif/esp-dev-kits/assets/22739578/8ca34745-56e6-470e-80ac-e58b53597052)
If so, I have to redraw. but it will have the risk of errors between related departments

**Comment by isthaison** [comment]
![image](https://github.com/espressif/esp-dev-kits/assets/22739578/1c5081a7-0ea2-4b58-a11f-fa1effd59289)
